/// Contiene los textos legales completos para los términos y condiciones de MyKids.

const String fullPrivacyTermsText = '''
TERMO DE CONSENTIMENTO COM O TRATAMENTO DE DADOS PESSOAIS E DE DADOS PESSOAIS SENSÍVEIS
Contrato original depositado no Sistema MyKids e em https://appmykids.com.br/lgpd/
Este Termo de Consentimento com o Tratamento de Dados Pessoais e de Dados Pessoais Sensíveis é uma autorização expressa celebrada entre você (TITULAR), qualificado no momento do cadastro no Aplicativo MyKids, inicialmente em uso pela IGREJA AMOR EM MOVIMENTO SAO PAULO, pessoa jurídica de direito privado, com sede à Rua Robert Bosch, 116 Parque Industrial Tomas Edson na cidade de São Paulo no estado de São Paulo, inscrita no CNPJ sob o nº 35.600.864/0001-29, e-mail de atendimento contato@igrejaamoremovimento.com.br (CONTROLADOR), para que CONTROLADOR e OPERADOR procedam com o tratamento de seus dados pessoais.

1 DAS DECLARAÇÕES
Ao aderir de forma plena e irrestrita ao presente Termo de Consentimento, você, TITULAR, declara sem quaisquer reservas que:
a) você, TITULAR, é pessoa maior e capaz, plenamente habilitado para quaisquer atos da vida civil, nos termos da legislação que lhe seja aplicável na jurisdição de sua residência;
 b) a sua adesão aos serviços do CONTROLADOR visa a um objeto lícito e possível;
 c) a sua adesão aos serviços do CONTROLADOR é feita de forma livre e desimpedida, sem qualquer situação de coação, pressão por parte de qualquer pessoa, erro, simulação ou estado de perigo;
 d) você, TITULAR, é o único destinatário dos serviços do CONTROLADOR e, caso solicite serviços para terceiros, coletou o expresso consentimento destes;
 e) você, TITULAR, estava presente no ato de criação do cadastro junto ao CONTROLADOR, em especial no ato de marcar a opção "Li e estou de acordo com os termos do contrato do CONTROLADOR", e recebeu confirmação imediata da aceitação ou não de seu cadastro;
 f) você, TITULAR, não é residente ou domiciliado em nenhum país no qual os serviços oferecidos pelo CONTROLADOR sejam considerados ilegais;
 g) os endereços, números de telefone e e-mail informados no ato da criação da conta e em atualizações posteriores do cadastro estão ativos e são monitorados por você, TITULAR, com frequência adequada;
 h) você, TITULAR, cumpriu e cumpre todos os nossos procedimentos necessários de validação e verificação de identidade e segurança.

2 DO SERVIÇO DE ATENDIMENTO AO TITULAR
O CONTROLADOR disponibiliza permanentemente a você, TITULAR, o Serviço de Atendimento ao Titular, por via do qual você pode sanar suas dúvidas e apresentar solicitações acerca de informações, reclamações, suspensão ou cancelamento dos serviços eletrônicos.
2.1 Cabe a você, TITULAR, acessar adequadamente o Serviço de Atendimento ao Titular, contando com as seguintes opções:
 a) telefone, disponível no horário comercial, tal como divulgado no site do CONTROLADOR e nos perfis das redes sociais;
 b) e-mail, a ser encaminhado por você, TITULAR, ao endereço divulgado no site do CONTROLADOR e no preâmbulo deste Termo de Consentimento.
2.2 Ao receber o seu contato pelos canais descritos no parágrafo anterior, o CONTROLADOR confirmará imediatamente o recebimento das suas demandas pelo mesmo meio empregado por você, TITULAR; caso a confirmação não seja recebida, caberá exclusivamente a você, TITULAR, representar a demanda, uma vez que o seu contato não foi recebido pelos nossos canais de comunicação.

3 DOS PRAZOS E DA VIGÊNCIA
Este Termo de Consentimento é celebrado por prazo indeterminado, entrando em vigor na data de sua aceitação por você, TITULAR, de forma presencial ou eletrônica.
3.1 O CONTROLADOR poderá modificar, adicionar ou remover quaisquer cláusulas ou condições deste Termo de Consentimento, nos termos do § 6º do art. 8º da Lei nº 13.709/2018, substituindo imediatamente a versão disponível no site pela versão mais atualizada e, quando a alteração implicar restrição das condições inicialmente pactuadas, o CONTROLADOR informará o TITULAR da mudança, por qualquer dos canais de comunicação disponíveis, com pelo menos 30 (trinta) dias de antecedência da entrada em vigor da alteração, podendo o TITULAR, nos casos em que o seu consentimento é exigido, revogá-lo caso discorde da alteração.
3.2 Você, TITULAR, reconhece expressamente ao aderir ao presente Termo de Consentimento que o disposto na Cláusula 2.1 não se aplica aos aspectos financeiros dos serviços do CONTROLADOR, de modo que taxas, cotações, tarifas, dízimos ou quaisquer remunerações devidas pelos serviços serão alteradas e informadas exclusivamente nos canais usuais do CONTROLADOR, e entrarão em vigor imediatamente a partir da data de sua alteração.
3.3 No caso de alterações, nos termos da presente Cláusula, você, TITULAR, poderá rescindir o presente contrato a qualquer tempo antes de entrar em vigor a alteração e, caso não o faça, entender-se-á que você, TITULAR, a aceitou tacitamente.
3.4 Com vistas a manter e atender os mais atuais requisitos da comunidade, de desenvolvimento tecnológico e de parâmetros legais, o CONTROLADOR poderá, a seu exclusivo critério e a qualquer tempo, alterar, tanto em forma como em conteúdo, suspender ou cancelar quaisquer dos serviços, produtos, utilidade ou aplicativo, disponibilizados por si ou por terceiros, inclusive com relação ao serviço e a qualquer dos serviços adicionais prestados nos termos deste Termo de Consentimento.

4 DO SIGILO E DA POLÍTICA DE PRIVACIDADE
Nas operações de coleta, armazenamento, guarda e tratamento de registros, de dados pessoais, de dados pessoais sensíveis ou de comunicações, o CONTROLADOR garante a você, TITULAR, que respeita a legislação brasileira e os direitos à privacidade, à proteção dos dados pessoais e ao sigilo das comunicações privadas e dos registros.
4.1 O CONTROLADOR garante que dados cadastrais do TITULAR não são vendidos, trocados ou divulgados para terceiros, exceto quando essas informações são necessárias para as atividades e serviços religiosos solicitados por você, TITULAR, uma vez que seus dados pessoais são fundamentais para a execução dos serviços oferecidos pelo CONTROLADOR.
4.2 As suas informações pessoais, TITULAR, serão tratadas com o nível de proteção legalmente exigível para garantir sua segurança e evitar alterações, perdas, tratamentos ou acessos não autorizados.
4.3 Para a prestação de serviços a você, TITULAR, o CONTROLADOR pode coletar as seguintes informações:
 a) informações pessoais proporcionadas por você, TITULAR, como nome e sobrenome, número de documento ou identificação válida, senha, nacionalidade, informações de identificação fiscal, informações físicas e virtuais de contato (como número de telefone, domicílio ou endereço de e-mail), informações e dados para a realização de pagamentos e informações de acesso a redes sociais e contas junto a terceiros, dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural, cuja verificação confidencial junto a terceiros você, TITULAR, desde já autoriza por meio deste contrato;
b) informações sobre você, TITULAR, proporcionadas por terceiros, como entidades religiosas, parceiros, entidades afiliadas, redes sociais e bases de dados públicas e privadas, que poderão ser combinadas com as suas informações pessoais para a prestação dos serviços do CONTROLADOR;
c) informações recolhidas pelos nossos sistemas, o que inclui o recolhimento e armazenamento automático de informações sobre a sua atividade, TITULAR, na internet, a URL da qual provém (estejam ou não no site do CONTROLADOR), a URL que acessa frequentemente, o navegador que utiliza e seu endereço IP, bem como os sites visitados e as buscas realizadas, a utilização de cookies e de web beacons.
4.4 Você, TITULAR, sempre poderá decidir não fornecer ao CONTROLADOR informações mas, em geral, são necessárias determinadas informações suas para a prestação de nossos serviços e atividades; caso decida não nos fornecer determinadas informações, é possível que você, TITULAR, não possa utilizar nossos serviços ou participar de atividades.
4.5 Em qualquer momento, você, TITULAR, poderá escolher não receber arquivos de cookies habilitando seu navegador ou seu dispositivo móvel para que os recuse ou lhe informe antes de aceitá-los; esteja ciente, no entanto, de que, ao se recusar a aceitar cookies ou outros dispositivos de coleta de informações, poderá não ter acesso aos serviços oferecidos pelo CONTROLADOR.
4.6 Na prestação de serviços a você, TITULAR, o CONTROLADOR poderá aplicar seus dados nas seguintes atividades:
a) gerenciar a prestação de serviços e a administração de atividades para você, TITULAR, e os membros de sua família incluídos em seu cadastro, realizar os processos que houver iniciado e processar documentos;
b) oferecer a você, TITULAR, produtos e serviços e responder suas perguntas e comentários;
c) enviar a você, TITULAR, confirmações e atualizações sobre seus serviços, bem como quaisquer informações respectivas relevantes, via aplicativo, e-mail, SMS ou WhatsApp ao telefone celular que você, TITULAR, tiver informado;
d) entrar em contato com você, TITULAR, para fins de prestar serviços, realizar pesquisas de opinião, estatísticas ou análises sobre hábitos ou preferências, notificá-lo por e-mail sobre os produtos e serviços que possam ser de seu interesse, exceto se você optar em contrário;
e) desenvolver estudos internos sobre os interesses, comportamentos e demografia dos Titulares e a comunidade, para compreender melhor suas necessidades e interesses, melhorar nossas iniciativas, personalizar seus conteúdos, sua apresentação e serviços, exibir informações e banners que sejam interessantes para os nossos usuários;
f) compartilhar suas informações pessoais com as entidades pertencentes à Instituição Religiosa do CONTROLADOR, sendo que o receptor de tais dados pessoais assumirá as mesmas obrigações correspondentes ao responsável que transfere esses dados pessoais;
g) publicar no site, em páginas de redes sociais ou em outros veículos de comunicação do CONTROLADOR as fotografias, opiniões, comentários, depoimentos e sugestões formulados por você, TITULAR, e pelos membros de sua família indicados no Aplicativo MyKids, que poderão ser identificados através de seu nome completo ou apelido, fotografia, comentário e nacionalidade;
h) garantir a segurança das crianças e adolescentes da família do TITULAR, entregando-as somente ao responsável que a deixou aos cuidados da equipe do CONTROLADOR;
i) comunicar-se com o responsável pela criança ou adolescente caso seja necessário;
j) coletar informações de vida e saúde como restrições alimentares ou necessidades especiais para acolher a criança da forma necessária e evitar situações que a coloquem em risco.
4.7 Ao enviar-nos suas opiniões, comentários, depoimentos e sugestões, ou fornecer fotografias reais através do site do CONTROLADOR ou do Aplicativo MyKids, você, TITULAR, cede de modo irrevogável ao CONTROLADOR todos os direitos de propriedade sobre tais fotografias e opiniões; você, TITULAR, pode enviar sua opinião de maneira anônima ou eliminá-la, comunicando-se com o SAT do CONTROLADOR nos moldes da Cláusula 2.
4.8 Assim como no caso do item anterior desta Cláusula, você, TITULAR, desde já confere consentimento expresso para que fotografias do ambiente de atividades em que você ou sua família, incluindo crianças e adolescentes, estejam junto ao CONTROLADOR, sejam divulgadas pelo CONTROLADOR em suas redes sociais e demais canais de comunicação, independentemente de autorização específica posterior.
4.9 Você, TITULAR, garante e responde, em qualquer caso, pela veracidade, exatidão, vigência e autenticidade das informações pessoais fornecidas, comprometendo-se a mantê-las devidamente atualizadas.
4.10 Você, TITULAR, deverá diligenciar e tomar todas as providências necessárias para impedir a divulgação de qualquer informação, bem como para evitar que tais informações confidenciais caiam em domínio público, sendo-lhe absolutamente vedado divulgar sua senha ou qualquer de seus dados de acesso a terceiros, ainda que parentes e amigos; o TITULAR não poderá divulgar de forma alguma as informações a terceiros, sendo que o CONTROLADOR não se responsabilizará por qualquer violação de privacidade ocorrida por culpa do TITULAR.
4.11 O TITULAR reconhece que o dever de sigilo se aplica de forma especial e reforçada em relação aos dados pessoais, religiosos, financeiros, bancários e tributários de outros Titulares do CONTROLADOR a que eventualmente tem, teve ou terá acesso no exercício de suas atividades, tendo o TITULAR dever reforçado de preservação absoluta de tais dados, sendo-lhe vedado utilizá-los em benefício ou prejuízo seu ou de terceiros.
4.12 Todas as suas informações pessoais, TITULAR, são recolhidas e armazenadas em servidores localizados fisicamente no Brasil e nos Estados Unidos; o CONTROLADOR poderá futuramente realocar tais servidores em qualquer outro país, e poderá armazenar as informações pessoais no Brasil, nos Estados Unidos ou em outros países, com fins de respaldo ou back-up, providências com as quais você, TITULAR, expressa e inequívocoamente consente.
4.13 Você, TITULAR, só receberá boletins, mensagens ou alertas de e-mail do CONTROLADOR ou do OPERADOR pois com isso expressamente concorda no ato de inscrição em nossos serviços, nos termos desta Cláusula; você poderá cancelar sua subscrição pelo link presente no próprio e-mail, ou comunicando-se com o SAT do CONTROLADOR nos moldes da Cláusula 2.
4.14 Os dados que o CONTROLADOR tenha sobre você, TITULAR, podem ser objeto de acesso, cancelamento, atualização, retificação e oposição, a ser exercida diretamente pelo acesso a seu cadastro, no site do CONTROLADOR, ou comunicando-se com o SAT do CONTROLADOR nos moldes da Cláusula 2.
4.15 Embora você, TITULAR, possa requerer o cancelamento de seu cadastro e a eliminação de suas informações pessoais, o CONTROLADOR ou
 informações prestadas em determinados casos, com a finalidade de resolver disputas ou reclamações, detectar problemas ou incidências e solucioná-los, e cumprir as disposições legais e contratuais aplicáveis; portanto, embora o CONTROLADOR comprometa-se a empregar os melhores esforços, poderá ocorrer que nem todas as informações pessoais sejam definitivamente eliminadas, podendo o CONTROLADOR, ainda, manter os seus dados para as seguintes finalidades:
a) cumprimento de obrigação legal ou regulatória pelo CONTROLADOR;
b) estudo por órgão de pesquisa, garantida, sempre que possível, a anonimização dos dados pessoais;
c) transferência a terceiro, desde que respeitados os requisitos de tratamento de dados dispostos em Lei;
d) uso exclusivo do CONTROLADOR, vedado seu acesso por terceiros, e desde que anonimizados os dados.
4.16 Você, TITULAR, declara ciência de que, passados um período de inatividade estabelecido pelo CONTROLADOR sem que você ou os membros de sua família interajam com o CONTROLADOR ou frequentem suas atividades, os dados serão anonimizados e, caso você, TITULAR, retorne a manter contato e relações com o CONTROLADOR, terá que renovar seu cadastro e seu consentimento.
4.17 Você, TITULAR, ao solicitar eletronicamente os serviços do CONTROLADOR ou ao instalar o Aplicativo MyKids, imediatamente concede consentimento, nos termos do art. 7º, inciso I, e do art. 8º da Lei nº 13.709/2018, para que o CONTROLADOR proceda com quaisquer formas legalmente permitidas de tratamento de seus dados pessoais, para as finalidades e nos parâmetros estipulados neste Termo de Consentimento.
4.18 Na qualidade de Controlador dos dados, o CONTROLADOR poderá ser contactado por você, TITULAR, para quaisquer informações referentes ao tratamento de seus dados pessoais, por via do SAT do CONTROLADOR nos moldes da Cláusula 2, podendo o Encarregado pelo Tratamento de Dados Pessoais do CONTROLADOR ser contactado nos termos indicados no site do CONTROLADOR.
4.19 Na qualidade de Titular dos dados, você, TITULAR, conta com os seguintes direitos, nos termos do art. 18 da Lei nº 13.709/2018:
a) confirmação da existência de tratamento;
b) acesso aos dados;
c) correção de dados incompletos, inexatos ou desatualizados;
d) anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade com o disposto na Lei;
e) portabilidade dos dados a outro fornecedor de serviço ou produto, mediante requisição expressa, de acordo com a regulamentação da autoridade nacional, observados os segredos comercial e industrial;
f) eliminação dos dados pessoais tratados com o consentimento do titular, exceto nas hipóteses previstas na Cláusula 2.14;
g) informação das entidades públicas e privadas com as quais o controlador realizou uso compartilhado de dados;
h) informação sobre a possibilidade de não fornecer consentimento e sobre as consequências da negativa;
i) revogação do consentimento a qualquer momento, mediante manifestação expressa nos termos da Cláusula 2.16, ratificados os tratamentos realizados sob amparo do consentimento anteriormente manifestado enquanto não houver requerimento de eliminação, nos termos desta Cláusula.
4.20 O tratamento de dados pessoais de crianças e de adolescentes, sob a sua guarda, TITULAR, deverá ser realizado em seu melhor interesse, nos termos deste Termo de Consentimento e a legislação pertinente, com especial atenção para a garantia de segurança das crianças e adolescentes nas atividades do CONTROLADOR.
4.21 Neste ato você, TITULAR, por este ato concede o consentimento específico e em destaque para o tratamento de dados pessoais de crianças sob sua guarda ou responsabilidade, na qualidade de pai, mãe ou responsável legal, incluindo o uso de seus dados para garantir o contato imediato com os pais ou responsáveis e a divulgação de imagem dos ambientes em que a criança ou adolescente apareça ou não.
4.22 Poderão ser coletados dados pessoais de crianças sem o consentimento a que se refere este Termo quando a coleta for necessária para contatar os pais ou o responsável legal, utilizados uma única vez e sem armazenamento, ou para sua proteção.
4.23 O CONTROLADOR deve realizar todos os esforços razoáveis para verificar que o consentimento dado por você, TITULAR, corresponde ao consentimento dado pelo responsável pela criança, consideradas as tecnologias disponíveis; de todo modo, você, TITULAR, desde já declara ser pai, mãe ou responsável legal da criança.
'''; 