// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5B9FFxJ0V-Tl9K5xnZFO-sqNtcmS6jTU',
    appId: '1:1039506776024:android:8614825b0835d80d341cad',
    messagingSenderId: '1039506776024',
    projectId: 'igreja-amor-em-movimento',
    storageBucket: 'igreja-amor-em-movimento.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGTdnIZ5m-zROkgb67iIL3AzXaBJFSbRQ',
    appId: '1:1039506776024:ios:0feee15e891f5eef341cad',
    messagingSenderId: '1039506776024',
    projectId: 'igreja-amor-em-movimento',
    storageBucket: 'igreja-amor-em-movimento.firebasestorage.app',
    iosBundleId: 'com.igrejamoremovimento.igreja',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRgDiR0VfJ3VjN38CdfXt_WK7VL-P8Go',
    appId: '1:1039506776024:web:cb0d7104def4f5c4341cad',
    messagingSenderId: '1039506776024',
    projectId: 'igreja-amor-em-movimento',
    authDomain: 'igreja-amor-em-movimento.firebaseapp.com',
    storageBucket: 'igreja-amor-em-movimento.firebasestorage.app',
    measurementId: 'G-YFJNLJD7M1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGTdnIZ5m-zROkgb67iIL3AzXaBJFSbRQ',
    appId: '1:1039506776024:ios:4ccb9f31b9f741a1341cad',
    messagingSenderId: '1039506776024',
    projectId: 'igreja-amor-em-movimento',
    storageBucket: 'igreja-amor-em-movimento.firebasestorage.app',
    iosBundleId: 'com.example.churchAppBr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRgDiR0VfJ3VjN38CdfXt_WK7VL-P8Go',
    appId: '1:1039506776024:web:12e8460350d8ad75341cad',
    messagingSenderId: '1039506776024',
    projectId: 'igreja-amor-em-movimento',
    authDomain: 'igreja-amor-em-movimento.firebaseapp.com',
    storageBucket: 'igreja-amor-em-movimento.firebasestorage.app',
    measurementId: 'G-869R4LDN7V',
  );

}